### ISSUE TITLE
Is there an API documentation ?

### ISSUE THREAD

**Issue by pommedeterresautee** [urieli/talismane#13]
I have seen command line documentation but no Java API documentation.
Is it published somewhere?

Kind regards,
Michaël

**Comment by urieli** [comment]
Good question. Not for now. I'll work on publishing it to github and answer here as soon as it's available.

**Comment by pommedeterresautee** [comment]
Thanks.

Just FYI I was looking for a simple example. I have noticed that your implementation in main is already multi threaded, but I want to take care of this part myself.

A (very) simple example like (in Scala syntax below) would be nice:
```scala
val modelPOS = POS.modelLoader("some path")
val modelDEP = DependencyPaser.modelLoader("some path2")
val posTagged = model.postag(aString)
val depTree = modelDEP.parse(posTagged)

// Call to some method to navigate in the dependency tree...

```
May be there are some class I may already look at to do what I want?

Kind regards,
Michaël

**Comment by urieli** [comment]
Ok, this is not particularly pretty as it stands in the current version of Talismane, but fairly straightforward. Here's an example. I'll try to make it prettier for a future version!

First, download the languagepack you want from the releases.
Then:

<code>
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.joliciel.talismane.GenericLanguageImplementation;
import com.joliciel.talismane.TalismaneConfig;
import com.joliciel.talismane.TalismaneService;
import com.joliciel.talismane.TalismaneServiceLocator;
import com.joliciel.talismane.parser.DependencyNode;
import com.joliciel.talismane.parser.ParseConfiguration;
import com.joliciel.talismane.parser.Parser;
import com.joliciel.talismane.posTagger.PosTagSequence;
import com.joliciel.talismane.posTagger.PosTagger;
import com.joliciel.talismane.tokeniser.TokenSequence;
import com.joliciel.talismane.tokeniser.Tokeniser;

public class TalismaneAPITest {

	public static void main(String[] args) {
		String languagePackPath = args[0];
		String text = "J'ai mangé trois pommes et une banane.";
		TalismaneServiceLocator talismaneServiceLocator = TalismaneServiceLocator.getInstance("");
		TalismaneService talismaneService = talismaneServiceLocator.getTalismaneService();
		GenericLanguageImplementation languageImplementation = GenericLanguageImplementation.getInstance("");
		File languagePackFile = new File(languagePackPath);
		languageImplementation.setLanguagePack(languagePackFile);
		Map<String,String> argMap = new HashMap<String, String>();
		argMap.put("command", "analyse");
		argMap.put("startModule", "tokeniser");
		argMap.put("endModule", "parser");
		TalismaneConfig talismaneConfig = talismaneService.getTalismaneConfig(argMap, languageImplementation);
		Tokeniser tokeniser = talismaneConfig.getTokeniser();
		List<TokenSequence> tokenSequences = tokeniser.tokenise(text);
		PosTagger posTagger = talismaneConfig.getPosTagger();
		PosTagSequence posTagSequence = posTagger.tagSentence(tokenSequences.get(0));
		System.out.println(posTagSequence);
		Parser parser = talismaneConfig.getParser();
		ParseConfiguration parseConfiguration = parser.parseSentence(posTagSequence);
		DependencyNode dependencyNode = parseConfiguration.getParseTree();
		System.out.println(dependencyNode);
	}

}
</code>

You can use the classes PosTagSequence to look at the postags, and the classes ParseConfiguration or DependencyNode to look at the parse. DependencyNode might be a bit more natural to work with, as it represents a tree structure (in this case anchored at the sentence root).

**Comment by urieli** [comment]
Added API client code example at https://github.com/urieli/talismane/blob/master/talismane_examples/src/com/joliciel/talismane/examples/TalismaneAPITest.java

Added JavaDoc API at http://urieli.github.io/talismane/api/
