### ISSUE TITLE
config files for versions 2.x.x

### ISSUE THREAD

**Issue by kroham** [urieli/talismane#21]
Hello,
can you please add default config files for previous versions (2.x.x) to your releases? Or if they are there but I missed them somehow, can please indicate their exact location?
Thank you very much in advance.

**Comment by urieli** [comment]
Talismane only started using config files in version 3.0.0.
Prior to this version, language packs needed to contain a file, languagePage.properties, with a pre-defined syntax indicating the filename for each resource type (lexicons, models, etc.).

You can see the basic execution command before and after at:
https://github.com/urieli/talismane/wiki/Home/_compare/90e220c50efb8a23b6361b93506d05a996a395ff...63e70d0e813ae0f346f9fa78052695b36571e584#diff-b4d7124d2993cd13aabeec1fc19baf51L41

**Comment by kroham** [comment]
got it, thank you!
