### ISSUE TITLE
Documentation : 2.1.2. From the sources using Git

### ISSUE THREAD

**Issue by jfaucon** [urieli/talismane#3]
Proposition :
Pour la section "2.1.2. From the sources using Git", la commande 
ant -lib=ant
ne fonctionne pas sous un système Linux.

Je propose d'ajouter la commande :
ant -lib ant/

Cela peut faire gagner du temps à ceux qui désirent compiler les sources sur Linux.

**Comment by urieli** [comment]
Fixed by jfaucon
