### ISSUE TITLE
Depend on official OpenNLP maxent

### ISSUE THREAD

**Issue by reckart** [urieli/talismane#6]
I'm trying to build talismane using Maven and using only dependencies available from Maven Central.

This is currently blocked by at least one customized JAR used in talismane. Would it be possible to maintain the classes "TwoPassRealValueDataIndexer" and "GISTrainer" as part of the talismane codebase (and in the talismane packages) instead of using a customized maxent jar? For "GISTrainer", it may also be useful to file an issue with Apache OpenNLP to ask them to make the class public.

**Comment by urieli** [comment]
Thanks for your Maven branch. We finally got around to merging this and making Talismane available through Maven (as of release v2.5.0b).
