### ISSUE TITLE
Depend on official liblinear

### ISSUE THREAD

**Issue by reckart** [urieli/talismane#7]
Talismane apparently uses a patched liblinear. However, it also appears to compile nicely against the official liblinear 1.94 available from Maven Central [1]. I did not find any documentation as to what has been modified in the customized version. 

Would it be feasible to use the official version of the library? 

What has been customized in the library that comes with talismane?

[1] http://search.maven.org/#artifactdetails%7Cde.bwaldvogel%7Cliblinear%7C1.94%7Cjar

**Comment by urieli** [comment]
Closed as of release 2.5.0b, with full Maven build & deploy.
